version: '3.8'

services:
  mongodb:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db'
    networks:
      - mongo
    restart: always

  orders:
    image: 'orders:latest'
    ports:
      - '8080:8080'
    networks:
      - mongo
    depends_on:
      - mongodb
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/mydatabase?authSource=admin

networks:
  mongo:
    driver: bridge

volumes:
  mongo-data:
    driver: local